Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/
Copyright (c) 2021 KOBOTEN kobot1010@gmail.com.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqUI_hvnVS6GE1Bu2c8NgH78TsUVEPki
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from skimage.io import imread, imshow, imsave

def white_b(extracted_image):
    origin_image = cv2.cvtColor(extracted_image, cv2.COLOR_BGR2RGB)

    image_gw = ((origin_image * (origin_image.mean() / origin_image.mean(axis=(0, 1))))
                 .clip(0, 255).astype(int))
    image_gw = np.float32(image_gw)
    #image_gw = cv2.cvtColor(image_gw, cv2.COLOR_RGB2BGR)
    #imsave("./gw.jpg", image_gw)

    return image_gw
