# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqUI_hvnVS6GE1Bu2c8NgH78TsUVEPki
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from skimage.io import imread, imshow, imsave

def white_b(extracted_image):
    origin_image = cv2.cvtColor(extracted_image, cv2.COLOR_BGR2RGB)

    image_gw = ((origin_image * (origin_image.mean() / origin_image.mean(axis=(0, 1))))
                 .clip(0, 255).astype(int))
    image_gw = np.float32(image_gw)
    #image_gw = cv2.cvtColor(image_gw, cv2.COLOR_RGB2BGR)
    #imsave("./gw.jpg", image_gw)

    return image_gw
